export const SAVE_USER = "save_active_user";
export const STORE_PRODUCTS = "store_products";
export const ADD_TO_CART = "add_to_cart";
export const RENDER_ITEM_AMOUNT = "render_item_amount";
export const ADD_ONE = "add_one";
export const TOTAL_AMOUNT = "total_amount";
export const ADMIN_TOTAL_SALES = "total_sales";
export const ADMIN_ORDER_QUANTITY = "order_quantity";
// export const ADMIN_ALL_USERS = "get_all_users";
